config/routes.rb
Rails.application.routes.draw do
  mount Lit::Engine => '/lit'
  mount Spree::Core::Engine, at: '/shop'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  
  root "screens#show", screen_name: "home"
  
  resources "songs", only: [:show, :create] do
    member do
      post "increment_downloads"
      post "increment_plays"
    end
  end
  
  resources "videos", only: [:create]

  resolve "Song" do |record|
    [:song, :id => record.slug]
  end
  
  resources "submissions", only: [:create]
  
  Spree::Core::Engine.routes.draw do
    resources "orders", only: [:create]
  end
  
  resource "search", only: [:show]
  
  get "/:screen_name(/:id)", to: "screens#show", as: "screen"

  ["Album", "Artist", "Genre", "Movie", "Playlist", "Video"].each do |class_name|
    resolve class_name do |record|
      identifier = record.respond_to?(:slug) ? record.slug : record.id
      [:screen, :screen_name => class_name.downcase, :id => identifier]
    end    
  end
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/album.rb
class Album < ApplicationRecord
  belongs_to :artist
  
  has_one_attached :cover
  
  has_many :songs
  
  include Slug
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  
  scope :recent, -> { order(:created_at => :desc) }
end

app/models/artist.rb
class Artist < ApplicationRecord
  has_many :albums
  has_many :songs
  
  has_many :videos
  
  has_one_attached :image
  
  has_and_belongs_to_many :genres
  
  include Slug
end

app/models/banner.rb
class Banner < ApplicationRecord
  has_one_attached :image
  has_one_attached :mobile_image
  validates_presence_of :name, :image
end

app/models/dashboard.rb
class Dashboard < ApplicationRecord
  belongs_to :featured_song, class_name: "Video"
  
  include Banners
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_and_belongs_to_many :artists
  
  include Slug
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_one_attached :poster
  
  scope :showing, -> { order(:starts => :asc) }
  scope :upcoming, -> { order(:starts => :asc) }
  
  include Youtube, Slug
  
  validates_presence_of :poster, :starts
end

app/models/playlist.rb
class Playlist < ApplicationRecord
  has_and_belongs_to_many :songs
  
  include Slug
  
  include Soundcloud
end

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :album, optional: true
  belongs_to :artist, optional: true
  
  scope :popular, -> { order(:plays => :desc) }

  has_and_belongs_to_many :genres
  
  has_one_attached :image
  has_one_attached :audio_file
  
  validates_presence_of :image, if: :published
  
  include Soundcloud
  include Slug, Submittable

  
  validate :audio_file_or_soundcloud
  
  def audio_file_or_soundcloud
    unless audio_file.present? || soundcloud.present?
      errors.add(:audio_file, "Either audio file or Soundcloud link must be present")
    end
  end
  
  
  def cover
    image.presence || album&.cover&.presence
  end
end

app/models/spree/basic_payment_method.rb
module Spree
  class BasicPaymentMethod < PaymentMethod::Check
    preference :instuctions_in_english, :text
    preference :instuctions_in_portugese, :text
  end
end

app/models/spree/basic_shipping_calculator.rb
module Spree
  class BasicShippingCalculator < ShippingCalculator
    def self.description
      "Free Shipping to Luanda and Digital Products"
    end

    def compute(package)
      0
    end

    def available? package
      ships_to_luanda?(package) || digital_product?(package)
    end

    private

      def ships_to_luanda? package
        package.order.ship_address.city == "Luanda"
      end

      def digital_product? package
        package.order.digital?
      end
  end
end

app/models/spree/state_change_decorator.rb
module Spree::StateChangeDecorator
  def self.prepended(base)
    base.after_create :send_digital_download_link
  end
  
  private
  
    def send_digital_download_link
      if order&.some_digital? && next_state == "completed"
        Spree::DigitalMailer.download_link(order).deliver_later
      end
    end
    
    def order
      stateful.order if stateful.is_a?(Spree::Payment)
    end
end

Spree::StateChange.prepend(Spree::StateChangeDecorator)

app/models/video.rb
class Video < ApplicationRecord
  belongs_to :artist, optional: true
  
  validates_presence_of :youtube
  
  default_scope { recent }
  
  include Youtube
  include Slug, Submittable
  
  def self.featured
    find(1)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Locale
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/screens_controller.rb
class ScreensController < ApplicationController
  def show
    render params[:screen_name]
  end

  rescue_from ActionView::MissingTemplate do
    render file: "#{Rails.root}/public/404.html", status: 404, layout: nil
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :set_song
  
  skip_before_action :verify_authenticity_token, 
    only: [:increment_plays, :increment_downloads]
    
  def show
    params[:screen_name] = "song"
    render "screens/song"
  end
  
  def increment_plays
    @song.increment! "plays"
  end
  
  def increment_downloads
    @song.increment! "downloads"
  end
  
  def create
    @submission = Song.new(song_params)
    @submission.save
    render "submissions/create"
  end
  
  private
  
    def set_song
      @song = Song.find_by_slug(params[:id])
    end
    
    def song_params
      params.require(:song).permit(:lyrics, :audio_file, :soundcloud)
    end
end

app/controllers/spree/checkout_controller_decorator.rb
module Spree::CheckoutControllerDecorator
  private

    def completion_route(custom_params = nil)
      spree.root_path
    end
end

Spree::CheckoutController.prepend(Spree::CheckoutControllerDecorator)

app/controllers/spree/orders_controller.rb
class Spree::OrdersController < ApplicationController
  def create
    if @previous = Spree::Order.incomplete.find_by_token(cookies.signed[:token])
      @previous.destroy!
    end

    @order = Spree::Order.create!(
      store: spree_current_store,
      currency: current_currency,
      confirmation_delivered: true, # skip confirmation email
      token: Spree::GenerateToken.new.call(Spree::Order)
    )
    
    @order.line_items.create!(
      quantity: 1, 
      variant_id: params[:variant_id]
    )
    @order.update_with_updater!

    cookies.signed[:token] = @order.token
    cookies.permanent.signed[:guest_token] = @order.token
    
    redirect_to checkout_path
  end
  
  private
  
    def spree_current_store
      Spree::Store.last
    end
  
    def current_currency
      if spree_current_store.default_currency.present?
        spree_current_store.default_currency
      else
        Spree::Config[:currency]
      end
    end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  def create
    @submission = Video.new(video_params)
    @submission.save
    render "submissions/create"
  end
  
  private
  
    def video_params
      params.require(:video).permit(:youtube)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def clip_to_aspect_ratio(image, aspect_ratio, html_class: "")
    percentage = 1/aspect_ratio * 100
    style = "width: 100%; padding-bottom: #{percentage}%; 
      background: url('#{url_for image}'); background-size: cover; background-position: center;"
    content_tag(:div, nil, style: style, class: html_class)
  end
  
  
  def current_path_under? path
    request.path.starts_with? path
  end
  
  
  def dashboard
    Dashboard.first || Dashboard.new
  end
  
  def featured_video
    dashboard.featured_song
  end
  
  
  def banner(slot = params[:screen_name])
    render "application/banner", banner: dashboard.banner_for(slot)
  end
end

app/helpers/seo_helper.rb
module SeoHelper
  def title
    [
      content_for(:title),
      content_for(:heading) || current_record&.name,
      content_for(:subheading),
      "ESTREIAS"
    ].compact.join(" | ")
  end
  
  private
  
    def current_record
      @song || @video || @album || @artist || @movie
    end
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/spree/address/_form.html.erb
<% address_id = address_type.chars.first %>

<div class="inner" data-hook=<%="#{address_type}_inner" %>>
  <div class="form-group" id=<%="#{address_id}firstname" %>>
    <%= form.label :firstname do %>
      <%= Spree.t(:first_name) %><abbr class="required" title="required">*</abbr>
    <% end %>
    <%= form.text_field :firstname, class: 'form-control', required: true %>
  </div>
  <div class="form-group" id=<%="#{address_id}lastname" %>>
    <%= form.label :lastname do %>
      <%= Spree.t(:last_name) %><abbr class="required" title="required">*</abbr>
    <% end %>
    <%= form.text_field :lastname, class: 'form-control', required: true %>
  </div>
  <% if Spree::Config[:company] %>
    <div class="form-group" id=<%="#{address_id}company" %>>
      <%= form.label :company, Spree.t(:company) %>
      <%= form.text_field :company, class: 'form-control' %>
    </div>
  <% end %>
  <div class="form-group" id=<%="#{address_id}address1" %>>
    <%= form.label :address1 do %>
      <%= Spree.t(:street_address) %><abbr class="required" title="required">*</abbr>
    <% end %>
    <%= form.text_field :address1, class: 'form-control required' %>
  </div>
  <div class="form-group" id=<%="#{address_id}address2" %>>
    <%= form.label :address2, Spree.t(:street_address_2) %>
    <%= form.text_field :address2, class: 'form-control' %>
  </div>
  <div class="form-group" id=<%="#{address_id}city" %>>
    <%= form.label :city do %>
      <%= Spree.t(:city) %><abbr class="required" title="required">*</abbr>
    <% end %>
    <%= form.text_field :city, class: 'form-control', required: true %>
  </div>

  <div class="form-group" id=<%="#{address_id}country" %>>
    <%= form.label :country_id do %>
      <%= Spree.t(:country) %><abbr class="required" title="required">*</abbr>
    <% end %>
    <span id=<%="#{address_id}country-selection" %>>
      <%= form.collection_select :country_id, available_countries, :id, :name, {}, { class: 'form-control', required: true } %>
    </span>
  </div>

  <% if Spree::Config[:address_requires_state] %>
    <div class="form-group" id=<%="#{address_id}state" %>>
      <% have_states = !address.country.states.empty? %>
      <%= form.label :state do %>
        <%= Spree.t(:state) %><abbr class='required' title="required" id=<%="#{address_id}state-required"%>>*</abbr>
      <% end %>

      <%== state_elements = [
         form.collection_select(:state_id, address.country.states,
                            :id, :name,
                            {include_blank: true},
                            {class: have_states ? 'form-control' : 'hidden',
                            required: have_states,
                            disabled: !have_states}) +
         form.text_field(:state_name,
                            class: !have_states ? 'form-control' : 'hidden',
                            required: !have_states,
                            disabled: have_states)
         ].join.gsub('"', "'").gsub("\n", "")
      %>
    </div>
      <noscript>
        <%= form.text_field :state_name, class: 'form-control', required: true %>
      </noscript>
  <% end %>

  <div class="form-group" id=<%="#{address_id}zipcode" %>>
    <%= form.label :zipcode do %>
      <%= Spree.t(:zip) %><% if address.require_zipcode? %><abbr class="required" title="required">*</abbr><% end %>
    <% end %>
    <%= form.text_field :zipcode, class: 'form-control', required: address.require_zipcode? %>
  </div>


  <div class="form-group" id=<%="#{address_id}phone" %>>
    <%= form.label :phone do %>
      <%= Spree.t(:phone) %><% if address.require_phone? %><abbr class="required" title="required">*</abbr><% end %>
    <% end %>
    <%= form.phone_field :phone, class: 'form-control', required: address.require_phone? %>
  </div>
  <% if Spree::Config[:alternative_shipping_phone] %>
    <div class="form-group" id=<%="#{address_id}altphone" %>>
      <%= form.label :alternative_phone, Spree.t(:alternative_phone) %>
      <%= form.phone_field :alternative_phone, class: 'form-control' %>
    </div>
  <% end %>
</div>

app/views/spree/checkout/_address.html.erb
<% @addresses = try_spree_current_user ? try_spree_current_user.addresses : [] %>

<div class="row" id="checkout_form_address">
  <% ['billing', 'shipping'].each do |address_type|
    address_name = "#{address_type[0...4]}_address" %>
    <div class="col-12 col-md-6 mb-16" data-hook="<%= address_type %>_fieldset_wrapper">
      <div class="card card-default" id="<%= address_type %>" data-hook>
        <%= render "sub_heading", text: Spree.t(address_type + '_address') %>

        <div class="card-body">
          <% if address_type == 'shipping' %>
            <div class="mb-0 form-check" data-hook="use_billing">
              <%= label_tag :order_use_billing, id: 'use_billing' do %>
                <%= check_box_tag 'order[use_billing]', '1', @order.shipping_eq_billing_address?, { class: 'form-check-input'} %>
                <%= Spree.t(:use_billing_address) %>
              <% end %>
            </div>
          <% end %>
          <% if @addresses.present? %>
          <div class="select_address">
            <div class="form-group">
              <% @addresses.each_with_index do |address, idx| %>
              <span class="d-block mb-2" id="<%= [address_type, dom_id(address)].join('_') %>">
                <label class="form-check-label">
                  <%= form.radio_button "#{address_name}_id", address.id, checked: (address.id == try_spree_current_user["#{address_name}_id"] || idx == 0) %> <%= address.to_s.html_safe %>
                </label>
                <a class="mb-3" href="<%= edit_address_path(address) %>" data-hook="edit_address"><%= Spree.t(:edit) %></a>
              </span>
              <% end %>
              <div class="form-check">
                <label class="form-check-label">
                  <%= form.radio_button "#{address_name}_id", 0, class: 'form-check-input' %> <%= Spree.t('address_book.other_address') %>
                </label>
              </div>
            </div>
          </div>
          <% end %>
          <%= form.fields_for address_name do |address_form| %>
            <div class="inner" data-hook=<%="#{address_type}_inner" %>>
              <%= render partial: 'spree/addresses/form', locals: {
                address_name: address_name,
                address_form: address_form,
                address_type: address_type,
                address: Spree::Address.default
              } %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
</div>

<div class="text-left form-buttons mt-4" data-hook="buttons">
  <%= submit_tag Spree.t(:save_and_continue), class: 'btn btn-lg btn-success' %>
  <% if try_spree_current_user %>
    <!-- <span data-hook="save_user_address" class='save-user-address-wrapper'>
      &nbsp; &nbsp;
      <%= check_box_tag 'save_user_address', '1', try_spree_current_user.respond_to?(:persist_order_address) %>
      <%= label_tag :save_user_address, Spree.t(:save_my_address) %>
    </span> -->
  <% end %>
</div>

app/views/spree/checkout/_confirm.html.erb
<div class="card" id="order_details" data-hook>
  <div class="card-header">
    <h3 class="card-title mb-0 h5"><%= Spree.t(:confirm) %></h3>
  </div>
  <div class="card-body">
    <%= render partial: 'spree/shared/order_details', locals: { order: @order } %>
  </div>
</div>

<div class="card text-right form-buttons mt-4" data-hook="buttons">
  <div class="card-body">
    <% if @order.using_store_credit? %>
      <%= button_tag Spree.t('store_credit.remove'), name: 'remove_store_credit', class: 'continue btn' %>
    <% end %>
    <%= submit_tag Spree.t(:place_order), class: 'btn btn-lg btn-success' %>
    <script>Spree.disableSaveOnClick();</script>
  </div>
</div>

app/views/spree/checkout/_delivery.html.erb
<div class="card" id='shipping_method' data-hook>
  <div class="card-body" data-hook="shipping_method_inner">
    <div id="methods">
      <%= form.fields_for :shipments do |ship_form| %>
        <div class="shipment">
          <%= render "sub_heading", text: Spree.t(:shipping_method) %>

          <ul class="list-group shipping-methods">
            <% ship_form.object.shipping_rates.each do |rate| %>
              <li class="list-group-item shipping-method">
                <label>
                  <%= ship_form.radio_button :selected_shipping_rate_id,
                    rate.id,
                    data: {
                      behavior: 'shipping-method-selector',
                      cost: rate.display_cost
                  } %>
                  <span class="rate-name text-base"><%= rate.name %></span>
                  <span class="badge badge-secondary rate-cost"><%= rate.display_cost %></span>
                </label>
              </li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <% if @differentiator.try(:missing?) %>
        <div class="shipment unshippable">
          <h3 class="stock-location mb-0 h5" data-hook="stock-location">
            <%= Spree.t(:unshippable_items) %>
          </h3>
          <table class="table stock-contents" data-hook="stock-missing">
            <colgroup>
              <col style="width: 10%;" />
              <col style="width: 60%;" />
              <col style="width: 10%;" />
              <col style="width: 20%;" />
            </colgroup>
            <thead>
              <th></th>
              <th align='left'><%= Spree.t(:item) %></th>
              <th><%= Spree.t(:qty) %></th>
              <th><%= Spree.t(:price) %></th>
            </thead>
            <tbody>
              <% @differentiator.missing.each do |variant, quantity| %>
                <tr class="stock-item">
                  <td class="item-image"><%= mini_image(variant) %></td>
                  <td class="item-name"><%= variant.name %></td>
                  <td class="item-qty"><%= quantity %></td>
                  <td class="item-price"><%= display_price(variant) %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      <% end %>
    </div>
  </div>
</div>

<div class="text-left mt-8" data-hook="buttons">
  <%= submit_tag Spree.t(:save_and_continue), class: 'btn btn-lg btn-success' %>
</div>

<%= javascript_include_tag 'spree/frontend/checkout/shipment' %>

app/views/spree/checkout/_payment.html.erb
<div class="card" id="payment" data-hook>
  <div class="card-header">
    <h3 class="card-title mb-0 h5">
      <%= render "sub_heading", text: Spree.t(:payment_information) %>
    </h3>
  </div>

  <div class="card-body" data-hook="checkout_payment_step">

    <ul class="list-group hidden" id="payment-method-fields" data-hook>
      <% @order.available_payment_methods.each do |method| %>
        <li class="list-group-item radio">
          <label>
            <%= radio_button_tag "order[payments_attributes][][payment_method_id]", method.id, method == @order.available_payment_methods.first %>
            <%= Spree.t(method.name, scope: :payment_methods, default: method.name) %>
          </label>
        </li>
      <% end %>
    </ul>

    <ul id="payment-methods" class="list-unstyled position-relative" data-hook>
      <% @order.available_payment_methods.each do |method| %>
        <li id="payment_method_<%= method.id %>" class="<%= 'last' if method == @order.available_payment_methods.last %>" data-hook>
          <fieldset>
            <%= render partial: "spree/checkout/payment/#{method.method_type}", locals: { payment_method: method } %>
          </fieldset>
        </li>
      <% end %>
    </ul>

  </div>
</div>

<div class="text-left form-buttons mt-8" data-hook="buttons">
  <div class="card-body">
    <%= submit_tag Spree.t(:confirm_order) %>
  </div>
</div>

app/views/spree/checkout/_summary.html.erb
<div class="table-responsive text-base">
  <table class="table" data-hook="order_summary">
    <tbody>
      <!-- <tr data-hook="item_total">
        <td><strong><%= Spree.t(:item_total) %>:</strong></td>
        <td><strong><%= order.display_item_total.to_html %></strong></td>
      </tr> -->

      <% if order.line_item_adjustments.nonzero.exists? %>
        <tbody data-hook="order_details_promotion_adjustments">
          <% order.line_item_adjustments.nonzero.promotion.eligible.group_by(&:label).each do |label, adjustments| %>
            <tr class="total">
              <td><%= label %></td>
              <td><%= Spree::Money.new(adjustments.sum(&:amount), currency: order.currency).to_html %></td>
            </tr>
          <% end %>
        </tbody>
      <% end %>

      <tbody data-hook="order_details_tax_adjustments">
        <% order.all_adjustments.nonzero.tax.eligible.group_by(&:label).each do |label, adjustments| %>
          <tr class="total">
            <td><%= label %></td>
            <td><%= Spree::Money.new(adjustments.sum(&:amount), currency: order.currency).to_html %></td>
          </tr>
        <% end %>
      </tbody>

      <% if order.passed_checkout_step?("address") && order.shipments.any? %>
        <tr data-hook="shipping_total">
          <td><%= Spree.t(:shipping_total) %>:</td>
          <% shipping_total = Spree::Money.new(order.shipments.to_a.sum(&:cost), currency: order.currency) %>
          <td data-hook='shipping-total' data-currency='<%= Money::Currency.find(order.currency).symbol %>' thousands-separator='<%= shipping_total.thousands_separator %>' decimal-mark='<%= shipping_total.decimal_mark %>'><%= shipping_total.to_html %></td>
        </tr>

        <% if order.shipment_adjustments.nonzero.exists? %>
          <tbody data-hook="order_details_shipment_promotion_adjustments">
            <% order.shipment_adjustments.nonzero.promotion.eligible.group_by(&:label).each do |label, adjustments| %>
              <tr class="total">
                <td><%= label %>:</td>
                <td><%= Spree::Money.new(adjustments.sum(&:amount), currency: order.currency).to_html %></td>
              </tr>
            <% end %>
          </tbody>
        <% end %>
      <% end %>

      <% if order.adjustments.nonzero.eligible.exists? %>
        <tbody id="summary-order-charges" data-hook>
          <% order.adjustments.nonzero.eligible.each do |adjustment| %>
          <% next if (adjustment.source_type == 'Spree::TaxRate') and (adjustment.amount == 0) %>
            <tr class="total">
              <td><%= adjustment.label %>:</td>
              <td><%= adjustment.display_amount.to_html %></td>
            </tr>
          <% end %>
        </tbody>
      <% end %>

      <tr data-hook="order_total">
        <td><%= Spree.t(:order_total) %>:</td>
        <td>
          <strong>
            <span id='summary-order-total' class="lead text-primary" data-currency="<%= Money::Currency.find(order.currency).symbol %>"><%= order.display_total.to_html %></span>
          </strong>
        </td>
      </tr>

      <% if order.using_store_credit? %>
        <tr data-hook="order_details_store_credit">
          <td><strong><%= Spree.t(:store_credit_name) %>:</strong></td>
          <td><span id='summary-store-credit'><%= order.display_total_applied_store_credit.to_html %></span></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/spree/checkout/edit.html.erb
<%= render "generic_masthead", background: false, banner: false, container: true do %>
  <div class="mb-20">
    <%= render "heading", text: Spree.t(:checkout) %>
    
    <% if @order.errors.any? || flash.any? %>
      <div class="bg-gray-6 px-6 py-4 text-base inline-block border-l-2 border-brand">
        <%= render partial: 'spree/shared/error_messages', locals: { target: @order } %>
        <%= flash_messages %>
      </div>
    <% end %>
  </div>
  
  <div class="flex flex-wrap-reverse w-full">
    <div class="w-full lg:w-1/2 lg:mr-12">
      <%= form_for @order, url: update_checkout_path(@order.state), html: {class: "form" } do |form| %>
        <% if @order.state == 'address' || !@order.email? %>
          <%= render "sub_heading", text: t(".customer_information") %>
          <div class="form-group mb-16">
            <%= form.label :email, t(".email") %><span class="required">*</span>
            <%= form.email_field :email, required: true, class: "block" %>
          </div>
        <% end %>
      
        <div>
          <%= form.hidden_field :state_lock_version %>
          <%= render @order.state, form: form %>
        </div>
      <% end %>
    </div>
    
    <% if @order.state != 'confirm' %>
      <div class="mb-16">
        <%= render "sub_heading", text: Spree.t(:order_summary) %>
        <%= render partial: 'summary', locals: { order: @order } %>
      </div>
    <% end %>
  </div>
<% end %>

app/views/spree/digitals/_digital.html.erb
<% if digital.attachment_file_name.present? %>
  <%= link_to digital.attachment_file_name, 
    main_app.url_for(digital.attachment) %>

  <% if digital.attachment_file_size.present? %>
    (<%= number_to_human_size(digital.attachment_file_size) %>)
  <% end %>
<% else %>
  <%= Spree.t(:broken_file, scope: 'digitals') %>
<% end %>

app/views/spree/products/_cart_form.html.erb
<div class="mt-8">
  <%= form_with url: orders_path, local: true do |f| %>
    <div class="row" id="inside-product-cart-form" data-hook="inside_product_cart_form" itemprop="offers" itemscope itemtype="https://schema.org/Offer">
      <% if @product.variants_and_option_values(current_currency).any? %>
        <div id="product-variants" class="col-lg-6 mt-4">
          <ul class="list-group">
            <% @product.variants_and_option_values(current_currency).each_with_index do |variant, index| %>
              <li class="list-group-item <%= "active" if index == 0 %>">
                <div class="form-check">
                  <%= radio_button_tag "variant_id", variant.id, index == 0,
                      'data-price' => variant.price_in(current_currency).money,
                      'data-in-stock' => variant.can_supply?,
                      'data-backordered' => variant.backordered?,
                      class: 'form-check-input'
                  %>
                  <%= label_tag "variant_id_#{ variant.id }", class: "form-check-label" do %>
                    <span class="variant-description">
                      <%= variant.options_text %>
                    </span>
                    <% if variant_price variant %>
                      <span class="price diff"><%= variant_price variant %></span>
                    <% end %>
                    <% unless variant.can_supply? %>
                      <span class="out-of-stock"><%= Spree.t(:out_of_stock) %></span>
                    <% end %>
                  <% end %>
                </div>
              </li>
            <% end%>
          </ul>
        </div>
      <% else %>
        <%= hidden_field_tag "variant_id", @product.master.id %>
      <% end %>

      <% if @product.price_in(current_currency) && !@product.price.nil? %>
        <div data-hook="product_price" class="col-lg-5 mt-4">
          <div id="product-price">
            <div>
              <div class="text-lg uppercase text-brand font-medium">
                <span class="font-bold">$</span>
                <%= display_price(@product).slice(1..nil) %>
              </div>
            </div>

            <% if @product.master.can_supply? %>
              <link itemprop="availability" href="https://schema.org/InStock" />
            <% elsif @product.variants.empty? %>
              <span class="out-of-stock d-block mt-2">
                <%= Spree.t(:out_of_stock) %>
              </span>
            <% end %>
            <% if @product.backordered? %>
              <div class="alert alert-warning" id="cart-backordered-info">
                <%= Spree.t(:backordered_info) %>
              </div>
            <% end %>
          </div>

          <% if @product.can_supply? %>
            <div class="mt-2">
              <%= f.submit Spree.t(:buy_now), class: "
                bg-brand text-background rounded px-6 py-2 inline-block
                text-lg uppercase font-bold tracking-wider
                hover:bg-gray-6 hover:text-brand" %>
            </div>
          <% end %>
        </div>
      <% else %>
        <div id="product-price">
          <div>
            <span class="price selling" itemprop="price"
              content="<%= @product.price_in(current_currency).amount.to_d %>">
              <%= Spree.t('product_not_available_in_this_currency') %>
            </span>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>
</p>